# Heisenberg: Datos Geográficos (Ubigeo)
# Este es un extracto de los principales departamentos y provincias de Perú.

UBIGEO_DATA = {
    "AMAZONAS": {
        "CHACHAPOYAS": ["CHACHAPOYAS", "ASUNCION", "BALSAS", "CHETO", "CHILIQUIN", "CHUQUIBAMBA", "GRANADA", "HUANCAS", "LA JALCA", "LEYMEBAMBA", "MAGDALENA", "MARISCAL CASTILLA", "MOLINOPAMPA", "MONTEVIDEO", "OLLEROS", "QUINJALCA", "SAN FRANCISCO DE DAGUAS", "SAN ISIDRO DE MAINO", "SOLOCO", "SONCHE"],
        "BAGUA": ["LA PECA", "ARAMANGO", "COPALLIN", "EL PARCO", "IMAZA"],
        "BONGARA": ["JUMBILLA", "COROSHA", "CUISPES", "FLORIDA", "JAZAN", "RECTA", "SAN CARLOS", "SHIPASBAMBA", "VALERA", "YAMBRASBAMBA"]
    },
    "ANCASH": {
        "HUARAZ": ["HUARAZ", "COCHABAMBA", "COLCABAMBA", "HUANCHAY", "JANGAS", "LA LIBERTAD", "OLLEROS", "PAMPAS GRANDE", "PARIACOTO", "PIRA", "TARICA"],
        "SANTA": ["CHIMBOTE", "CACERES DEL PERU", "COISHCO", "MACATE", "MORO", "NEPEÑA", "SAMANCO", "SANTA", "NUEVO CHIMBOTE"],
        "HUARI": ["HUARI", "ANRA", "CAJAY", "CHAVIN DE HUANTAR", "HUACACHI", "HUACCHIS", "HUACHIS", "HUANTAR", "MASIN", "PAUCAS", "PONTO", "RAHUAPAMPA", "RAPAYAN", "SAN MARCOS", "SAN NICOLAS", "UCO"]
    },
    "AREQUIPA": {
        "AREQUIPA": ["AREQUIPA", "ALTO SELVA ALEGRE", "CAYMA", "CERRO COLORADO", "CHARACATO", "CHIGUATA", "JACOBO HUNTER", "LA JOYA", "MARIANO MELGAR", "MIRAFLORES", "MOLLEBAYA", "PAUCARPATA", "POCSI", "POLOBAYA", "QUEQUEÑA", "SABANDIA", "SACHACA", "SAN JUAN DE SIGUAS", "SAN JUAN DE TARUCANI", "SANTA ISABEL DE SIGUAS", "SANTA RITA DE SIGUAS", "SOCABAYA", "TIABAYA", "UCHUMAYO", "VITOR", "YANAHUARA", "YARABAMBA", "YURA", "JOSE LUIS BUSTAMANTE Y RIVERO"],
        "CAMANA": ["CAMANA", "JOSE MARIA QUIMPER", "MARIANO NICOLAS VALCARCEL", "MARISCAL CACERES", "NICOLAS DE PIEROLA", "OCAÑA", "QUILCA", "SAMUEL PASTOR"],
        "CAYLLOMA": ["CHIVAY", "ACHOMA", "CABANACONDE", "CALLALLI", "CAYLLOMA", "COPORAQUE", "HUAMBO", "HUANCA", "ICHUPAMPA", "LARI", "LLUTA", "MACA", "MADRIGAL", "SAN ANTONIO DE CHUCA", "SIBAYO", "TAPAY", "TISCO", "TUTI", "YANQUE", "MAJES"]
    },
    "AYACUCHO": {
        "HUAMANGA": ["AYACUCHO", "ACOCRO", "ACOS VINCHOS", "CARMEN ALTO", "CHIARA", "OCROS", "PACAYCASA", "QUINUA", "SAN JOSE DE TICLLAS", "SAN JUAN BAUTISTA", "SANTIAGO DE PISCHA", "SOCOS", "TAMBILLO", "VINCHOS", "JESUS NAZARENO"],
        "HUANTA": ["HUANTA", "AYAHUANCO", "HUAMANGUILLA", "IGUAIN", "LURICOCHA", "SANTILLANA", "SIVIA", "LLOCHEGUA"]
    },
    "CAJAMARCA": {
        "CAJAMARCA": ["CAJAMARCA", "CAJAMARCA", "ASUNCION", "CHETILLA", "COSPAN", "ENCAÑADA", "JESUS", "LLACANORA", "LOS BAÑOS DEL INCA", "MAGDALENA", "MATARA", "NAMORA", "SAN JUAN"],
        "CHOTA": ["CHOTA", "ANGUIA", "CHADIN", "CHALAMARCA", "CHIGUIRIP", "CHIMBAN", "CHOROPAMPA", "COCHABAMBA", "CONCHAN", "HUAMBOS", "LAJAS", "LLAMA", "MIRACOSTA", "PACCHA", "PION", "QUEROCOTO", "SAN JUAN DE LICUPIS", "TACABAMBA", "TOCMOCHE"]
    },
    "CUSCO": {
        "CUSCO": ["CUSCO", "CCORCA", "POROY", "SAN JERONIMO", "SAN SEBASTIAN", "SANTIAGO", "SAYLLA", "WANCHAQ"],
        "URUBAMBA": ["URUBAMBA", "CHINCHERO", "HUAYLLABAMBA", "MACHUPICCHU", "MARAS", "OLLANTAYTAMBO", "YUCAY"],
        "LA CONVENCION": ["SANTA ANA", "ECHARATE", "HUAYOPATA", "MARANURA", "OCOBAMBA", "QUELLOUNO", "QUIMBIRI", "SANTA TERESA", "VILCABAMBA", "PICHARI"]
    },
    "HUANUCO": {
        "HUANUCO": ["HUANUCO", "AMARILIS", "CHINCHAO", "CHURUBAMBA", "MARGOS", "QUISQUI", "SAN FRANCISCO DE CAYRAN", "SAN PEDRO DE CHAULAN", "SANTA MARIA DEL VALLE", "YARUMAYO", "PILLCO MARCA"]
    },
    "ICA": {
        "ICA": ["ICA", "LA TINGUIÑA", "LOS AQUIJES", "OCUCAJE", "PACHACUTEC", "PARCONA", "PUEBLO NUEVO", "SALAS", "SAN JOSE DE LOS MOLINOS", "SAN JUAN BAUTISTA", "SANTIAGO", "SUBTANIALLA", "TATE", "YAUCA DEL ROSARIO"]
    },
    "JUNIN": {
        "HUANCAYO": ["HUANCAYO", "CARHUACALLANGA", "CHACAPAMPA", "CHICCHE", "CHILCA", "CHONGOS ALTO", "CHUPURO", "COLCA", "CULLHUAS", "EL TAMBO", "HUACRAPUQUIO", "HUALHUAS", "HUANCAN", "HUASICANCHA", "HUAYUCACHI", "INGENIO", "PARIAHUANCA", "PILCOMAYO", "PUCARA", "QUICHUAY", "QUILCAS", "SAN AGUSTIN", "SAN JERONIMO DE TUNAN", "SAÑO", "SAPALLANGA", "SICAYA", "VIQUES"],
        "CHANCHAMAYO": ["LA MERCED", "SAN RAMON", "VITOC", "SAN LUIS DE SHUARO", "PICHANAKI", "PERENE"]
    },
    "LA LIBERTAD": {
        "TRUJILLO": ["TRUJILLO", "EL PORVENIR", "FLORENCIA DE MORA", "HUANCHACO", "LA ESPERANZA", "LAREDO", "MOCHE", "POROTO", "SALAVERRY", "SIMBAL", "VICTOR LARCO HERRERA"],
        "ASCOPE": ["ASCOPE", "CHICAMA", "CHOCOPE", "MAGDALENA DE CAO", "PAIJAN", "RAZURI", "SANTIAGO DE CAO", "CASA GRANDE"]
    },
    "LAMBAYEQUE": {
        "CHICLAYO": ["CHICLAYO", "CHONGOYAPE", "ETEN", "ETEN PUERTO", "JOSE LEONARDO ORTIZ", "LA VICTORIA", "LAGUNAS", "MONSEFU", "NUEVA ARICA", "OYOTUN", "PICSI", "PIMENTEL", "REQUE", "SANTA ROSA", "SAÑA", "CAYALTI", "PATAPO", "POMALCA", "PUCALA", "TUMAN"]
    },
    "LIMA": {
        "LIMA": ["LIMA", "ANCON", "ATE", "BARRANCO", "BREÑA", "CARABAYLLO", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESUS MARIA", "LA MOLINA", "LA VICTORIA", "LINCE", "LURIGANCHO", "LURIN", "MAGDALENA DEL MAR", "MIRAFLORES", "PACHACAMAC", "PUCUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RIMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFLOWERS", "SAN LUIS", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARIA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VILLA EL SALVADOR", "VILLA MARIA DEL TRIUNFO"],
        "CAÑETE": ["SAN VICENTE DE CAÑETE", "ASIA", "CALANGO", "CERRO AZUL", "CHILCA", "COAYLLO", "IMPERIAL", "LUNAHUANA", "MALA", "NUEVO IMPERIAL", "PACARAN", "QUILMANA", "SAN ANTONIO", "SAN LUIS", "SANTA CRUZ DE FLORES", "ZUÑIGA"],
        "HUAURA": ["HUACHO", "AMBAR", "CALETA DE CARQUIN", "CHECRAS", "HUALMAY", "HUAURA", "LEONCIO PRADO", "PACCHO", "SANTA MARIA", "SAYAN", "VEGUETA"]
    },
    "LORETO": {
        "MAYNAS": ["IQUITOS", "ALTO NANAY", "FERNANDO LORES", "INDIANA", "LAS AMAZONAS", "MAZAN", "NAPO", "PUNCHANA", "TORRES CAUSANA", "BELEN", "SAN JUAN BAUTISTA"]
    },
    "PIURA": {
        "PIURA": ["PIURA", "CASTILLA", "CATACAOS", "CURA MORI", "LA ARENA", "LA UNION", "LAS LOMAS", "TAMBO GRANDE", "VEINTISEIS DE OCTUBRE"],
        "TALARA": ["PARIÑAS", "EL ALTO", "LA BREA", "LOBITOS", "MANCORA", "LOS ORGANOS"]
    },
    "PUNO": {
        "PUNO": ["PUNO", "ACORA", "AMANTANI", "ATUNCOLLA", "CAPACHICA", "CHUCUITO", "COATA", "HUATA", "MAÑAZO", "PAUCARCOLLA", "PICHACANI", "PLATERIA", "SAN ANTONIO", "TIQUILLACA", "VILQUE"]
    },
    "SAN MARTIN": {
        "MOYOBAMBA": ["MOYOBAMBA", "CALZADA", "HABANA", "JEBEROS", "SORITOR", "YANTALO"]
    },
    "TACNA": {
        "TACNA": ["TACNA", "ALTO DE LA ALIANZA", "CALANA", "INCLAN", "PACHIA", "PALCA", "POCOLLAY", "SAMA", "CIUDAD NUEVA", "CORONEL GREGORIO ALBARRACIN LANCHIPA"]
    }
}
